name: '${project.name}'
main: com.winterhavenmc.deathban.PluginMain
author: '${project.author}'
version: '${project.version}'
softdepend: [Multiverse-Core]
api-version: 1.16

commands:
  deathban:
    description: "This is the DeathBan base command."
    aliases: sdb
    usage: "/deathban [command]"

permissions:
  deathban.exempt:
    description: "Allow player exemption from death ban."
    default: op

  deathban.help:
    description: "Allow use of the help subcommand."
    default: op

  deathban.reload:
    description: "Allow use of the reload subcommand."
    default: op

  deathban.status:
    description: "Allow use of the status subcommand."
    default: op

  deathban.admin:
    description: "Give access to DeathBan admin commands."
    default: op
    children:
      deathban.expempt: true
      deathban.help: true
      deathban.reload: true
      deathban.status: true
